name: screenshot_maker
description: A Flutter package to take screenshots of various sizes.
version: 0.0.1
author: Oka Ryunoske
homepage: https://twitter.com/agajo_tech

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

flutter: